import type { Metadata } from "next";

// Generated by scripts/write-og-layouts.mjs — edit scripts/og-articles.mjs
// and re-run instead of hand-editing.
export const metadata: Metadata = {
  title: "Zero-Click Is Here: Getting Found When Nobody Visits Your Site",
  openGraph: {
    title: "Zero-Click Is Here: Getting Found When Nobody Visits Your Site",
    type: "article",
    images: [
      {
        url: "/og/zero-click-visibility.jpg",
        width: 1200,
        height: 630,
        type: "image/jpeg",
        alt: "Zero-Click Is Here: Getting Found When Nobody Visits Your Site",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    images: ["/og/zero-click-visibility.jpg"],
  },
};

export default function ArticleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
