import type { Metadata } from "next";

// Generated by scripts/write-og-layouts.mjs — edit scripts/og-articles.mjs
// and re-run instead of hand-editing.
export const metadata: Metadata = {
  title: "From 13 Days to 27 Minutes: Rebuilding the Content Pipeline",
  openGraph: {
    title: "From 13 Days to 27 Minutes: Rebuilding the Content Pipeline",
    type: "article",
    images: [
      {
        url: "/og/ai-content-pipeline.jpg",
        width: 1200,
        height: 630,
        type: "image/jpeg",
        alt: "From 13 Days to 27 Minutes: Rebuilding the Content Pipeline",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    images: ["/og/ai-content-pipeline.jpg"],
  },
};

export default function ArticleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
