import type { Metadata } from "next";

// Generated by scripts/write-og-layouts.mjs — edit scripts/og-articles.mjs
// and re-run instead of hand-editing.
export const metadata: Metadata = {
  title: "After Sora: The Best Brand Video Now Comes From a Stack",
  openGraph: {
    title: "After Sora: The Best Brand Video Now Comes From a Stack",
    type: "article",
    images: [
      {
        url: "/og/ai-video-stack.jpg",
        width: 1200,
        height: 630,
        type: "image/jpeg",
        alt: "After Sora: The Best Brand Video Now Comes From a Stack",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    images: ["/og/ai-video-stack.jpg"],
  },
};

export default function ArticleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
