import type { Metadata } from "next";

// Generated by scripts/write-og-layouts.mjs — edit scripts/og-articles.mjs
// and re-run instead of hand-editing.
export const metadata: Metadata = {
  title: "Native Audio: The Year AI Learned to Score Its Own Footage",
  openGraph: {
    title: "Native Audio: The Year AI Learned to Score Its Own Footage",
    type: "article",
    images: [
      {
        url: "/og/ai-native-audio.jpg",
        width: 1200,
        height: 630,
        type: "image/jpeg",
        alt: "Native Audio: The Year AI Learned to Score Its Own Footage",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    images: ["/og/ai-native-audio.jpg"],
  },
};

export default function ArticleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
