"use client";

import { useState } from "react";
import { m, AnimatePresence } from "framer-motion";
import JsonLd from "@/components/JsonLd";

const faqItems = [
  {
    question: "What is AI video generation and how does it work?",
    answer:
      "AI video generation uses machine learning models to create, edit, and enhance video content. At DT+C, we integrate AI video tools into our production pipeline to deliver campaign-ready footage faster and at a fraction of traditional production costs, while maintaining cinematic quality.",
  },
  {
    question: "What is GEO (Generative Engine Optimization)?",
    answer:
      "GEO is the practice of optimizing your brand’s content to appear in AI-powered search results from tools like ChatGPT, Perplexity, and Google AI Overviews. Unlike traditional SEO, GEO focuses on structured data, authoritative content, and citation-worthy writing that AI engines prefer to reference.",
  },
  {
    question:
      "How much does AI product visualization cost compared to traditional photography?",
    answer:
      "AI product visualization typically costs 80–95% less than traditional photo shoots. Where a conventional product shoot might run $20,000–$150,000+, AI-generated product imagery can achieve photorealistic results for a fraction of that, with faster turnaround and unlimited variations.",
  },
  {
    question: "What services does DT+C offer?",
    answer:
      "We offer strategy-led creative production including 3D animation, AI video generation, VFX, sound design, product visualization, short-form social content, brand identity systems, and full-service content pipelines. Everything is built on AI-native workflows for speed and quality.",
  },
  {
    question: "How long does a typical project take?",
    answer:
      "Most projects deliver initial concepts within 1–2 weeks and final assets within 3–6 weeks, depending on scope. Our AI-powered pipeline moves significantly faster than traditional production, often cutting timelines by 50–70%.",
  },
  {
    question: "What is AI-native brand identity?",
    answer:
      "AI-native brand identity replaces static brand guidelines with dynamic, AI-driven visual systems. Your brand’s visual DNA is encoded into AI workflows so every piece of content maintains consistency automatically, whether generated by humans or AI, across every platform and touchpoint.",
  },
];

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqItems.map((item) => ({
    "@type": "Question",
    name: item.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: item.answer,
    },
  })),
};

const easePrism = [0.52, 0.01, 0, 1] as const;

function FAQItem({
  question,
  answer,
  isOpen,
  onToggle,
}: {
  question: string;
  answer: string;
  isOpen: boolean;
  onToggle: () => void;
}) {
  return (
    <div className="border-b border-ash-border">
      <button
        onClick={onToggle}
        className="group flex w-full items-start justify-between gap-8 py-8 text-left cursor-pointer"
        aria-expanded={isOpen}
      >
        <span className="font-body font-normal text-body-lg text-bone">
          {question}
        </span>
        <m.span
          animate={{ rotate: isOpen ? 45 : 0 }}
          transition={{ duration: 0.5, ease: easePrism }}
          className="flex-shrink-0 mt-[0.05em] text-bone text-2xl font-normal leading-none select-none transition-colors duration-500 ease-prism group-hover:text-fog-blue"
          aria-hidden="true"
        >
          +
        </m.span>
      </button>
      <AnimatePresence initial={false}>
        {isOpen && (
          <m.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.5, ease: easePrism }}
            className="overflow-hidden"
          >
            <p className="max-w-[640px] font-body font-normal text-body-sm text-fog-blue pb-8">
              {answer}
            </p>
          </m.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section className="section-container section-padding">
      <JsonLd data={faqSchema} />
      <div className="max-w-3xl">
        <m.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.5, ease: easePrism }}
          className="mb-16 md:mb-24"
        >
          <span className="block text-caption uppercase tracking-[0.02em] font-normal text-fog-blue mb-6">
            FAQ
          </span>
          <h2 className="font-headline font-semibold uppercase text-h2 headline-cyan mb-8">
            Frequently Asked Questions
          </h2>
          <p className="max-w-[640px] font-body font-normal text-body-sm text-fog-blue">
            Everything you need to know about working with DT+C.
          </p>
        </m.div>
        <m.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.5, delay: 0.2, ease: easePrism }}
          className="border-t border-ash-border"
        >
          {faqItems.map((item, index) => (
            <FAQItem
              key={index}
              question={item.question}
              answer={item.answer}
              isOpen={openIndex === index}
              onToggle={() =>
                setOpenIndex(openIndex === index ? null : index)
              }
            />
          ))}
        </m.div>
      </div>
    </section>
  );
}
