"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import JsonLd from "@/components/JsonLd";

const faqItems = [
  {
    question: "What is AI video generation and how does it work?",
    answer:
      "AI video generation uses machine learning models to create, edit, and enhance video content. At DT+C, we integrate AI video tools into our production pipeline to deliver campaign-ready footage faster and at a fraction of traditional production costs, while maintaining cinematic quality.",
  },
  {
    question: "What is GEO (Generative Engine Optimization)?",
    answer:
      "GEO is the practice of optimizing your brand\u2019s content to appear in AI-powered search results from tools like ChatGPT, Perplexity, and Google AI Overviews. Unlike traditional SEO, GEO focuses on structured data, authoritative content, and citation-worthy writing that AI engines prefer to reference.",
  },
  {
    question:
      "How much does AI product visualization cost compared to traditional photography?",
    answer:
      "AI product visualization typically costs 80\u201395% less than traditional photo shoots. Where a conventional product shoot might run $20,000\u2013$150,000+, AI-generated product imagery can achieve photorealistic results for a fraction of that, with faster turnaround and unlimited variations.",
  },
  {
    question: "What services does DT+C offer?",
    answer:
      "We offer strategy-led creative production including 3D animation, AI video generation, VFX, sound design, product visualization, short-form social content, brand identity systems, and full-service content pipelines. Everything is built on AI-native workflows for speed and quality.",
  },
  {
    question: "How long does a typical project take?",
    answer:
      "Most projects deliver initial concepts within 1\u20132 weeks and final assets within 3\u20136 weeks, depending on scope. Our AI-powered pipeline moves significantly faster than traditional production, often cutting timelines by 50\u201370%.",
  },
  {
    question: "What is AI-native brand identity?",
    answer:
      "AI-native brand identity replaces static brand guidelines with dynamic, AI-driven visual systems. Your brand\u2019s visual DNA is encoded into AI workflows so every piece of content maintains consistency automatically, whether generated by humans or AI, across every platform and touchpoint.",
  },
];

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqItems.map((item) => ({
    "@type": "Question",
    name: item.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: item.answer,
    },
  })),
};

function FAQItem({
  question,
  answer,
  isOpen,
  onToggle,
}: {
  question: string;
  answer: string;
  isOpen: boolean;
  onToggle: () => void;
}) {
  return (
    <div className="border-b border-white/10">
      <button
        onClick={onToggle}
        className="flex w-full items-center justify-between py-6 text-left cursor-pointer"
        aria-expanded={isOpen}
      >
        <span className="font-headline text-lg md:text-xl text-pure-white pr-8">
          {question}
        </span>
        <motion.span
          animate={{ rotate: isOpen ? 45 : 0 }}
          transition={{ duration: 0.2, ease: "easeInOut" }}
          className="flex-shrink-0 text-electric-indigo text-2xl font-light select-none"
        >
          +
        </motion.span>
      </button>
      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
            className="overflow-hidden"
          >
            <p className="font-body text-cool-gray pb-6 pr-12 leading-relaxed">
              {answer}
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section className="section-container section-padding">
      <JsonLd data={faqSchema} />
      <div className="max-w-3xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
          className="text-center mb-12"
        >
          <h2 className="font-headline text-3xl md:text-5xl text-pure-white mb-4">
            Frequently Asked Questions
          </h2>
          <p className="font-body text-cool-gray text-lg">
            Everything you need to know about working with DT+C.
          </p>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="border-t border-white/10"
        >
          {faqItems.map((item, index) => (
            <FAQItem
              key={index}
              question={item.question}
              answer={item.answer}
              isOpen={openIndex === index}
              onToggle={() =>
                setOpenIndex(openIndex === index ? null : index)
              }
            />
          ))}
        </motion.div>
      </div>
    </section>
  );
}
